version: '2'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      SERVICE_NAME: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181


  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://$DOCKER_IP:9092"
      KAFKA_CREATE_TOPICS:

  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    ports:
      - 8081:8081
    links:
      - zookeeper:zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
    depends_on:
      - zookeeper
      - kafka
